# 'store_id': {'store_name': , 'store_category': , 'sub_categories': }

categories = {
    'womensclothing': "Women's Clothing",
    'girlsclothing': "Girls' Clothing",
    'babyclothing': "Baby Clothing",
    'boysclothing': "Boys' Clothing",
    'mensclothing': "Men's Clothing",
    'standard': 'Standard Screen',
    'imax': 'IMAX Screen',
    'asian': 'Asian',
    'sandwiches': 'Burgers & Sandwiches',
    'mexican': 'Mexican',
    'pizza': 'Pizza',
    'mediterranean': 'Mediterranean',
    'snacks': 'Snacks',
    'juice': 'Juices & Smoothies',
    'womensshoes': "Women's Shoes",
    'mensshoes': "Men's Shoes",
    'purses': "Purses",
    'neckwear': "Neckwear",
    'cellphones': "Cell Phones",
    'computers': "Computers",
    'phoneaccessories': "Phone accessories",
    'videogames': "Video Games",
    'internetprov': "Internet Providers",
    'home': "Home",
    'pets': "Pets",
    'books': "Books",
    'collectibles': "Collectible Items",
    'miscgifts': "Miscellaneous Gifts",
    'musicalinst': "Musical Instruments",
    'photography': "Photography",
    'toys': "Toys",
    'cologneperfume': "Cologne & Perfume",
    'hair': "Hair",
    'health': "Health",
    'nails': "Nails",
    'everyday': "Everyday Jewelry",
    'watches': "Watches",
    'fine': "Fine Jewelry",
    'bathrooms': "Bathrooms",
    }

stores = {
    '2love': {
        'store_name': '2 Love', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkeys': [102],
        },
    '2loveshoes': {
        'store_name': 'Shoes 2 Love', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes'],
        'mapkeys': [66],
        },  
    '2020': {
        'store_name': '20/20', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkeys': [120],
        },
    'accesoryshop': {
        'store_name': 'The Accesory Shop', 
        'store_category': 'accessories', 
        'sub_categories': ['purses'],
        'mapkeys': [89],
        },  
    'asianapps': {
        'store_name': 'Asian Apps +', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkeys': [113],
        },
    'att': {
        'store_name': 'AT&T', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkeys': [108],
        },
    'bathbodyworks': {
        'store_name': 'Bath & Body Works', 
        'store_category': 'home', 
        'sub_categories': ['home'],
        'mapkeys': [61],
        },  
    'bazzar': {
        'store_name': 'The Bazzar', 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkeys': [45],
        },
    'bbb': {
        'store_name': 'BedBath&Beyond', 
        'store_category': 'home', 
        'sub_categories': ['home'],
        'mapkeys': [42],
        },
    'boost': {
        'store_name': 'Boost Mobile', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkeys': [54],
        },
    'browspa24': {
        'store_name': 'Brow Spa 24', 
        'store_category': 'beauty', 
        'sub_categories': ['nails'],
        'mapkeys': [107],
        },
    'caferio': {
        'store_name': 'Cafe Rio', 
        'store_category': 'food', 
        'sub_categories': ['mexican'],
        'mapkeys': [30],
        },
    'cafezupas': {
        'store_name': 'Cafe Zupas', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [25],
        },
    'cellagain': {
        'store_name': 'Cell Again', 
        'store_category': 'electronics', 
        'sub_categories': ['phoneaccessories'],
        'mapkeys': [100],
        },
    # 'centurylink': {
    #     'store_name': 'CenturyLink', 
    #     'store_category': 'electronics', 
    #     'sub_categories': ['internetprov'],
    #     'mapkeys': [111],
    #     },
    'charleysalon': {
        'store_name': 'Charley Salon', 
        'store_category': 'beauty', 
        'sub_categories': ['hair'],
        'mapkeys': [118],
        },
    'childrensplace': {
        'store_name': "The Children's Place", 
        'store_category': 'clothing', 
        'sub_categories': ['boysclothing', 'girlsclothing', 'babyclothing'],
        'mapkeys': [19],
        },
    'chinesegourmetexpress': {
        'store_name': 'Chinese Gourmet Express', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkeys': [71],
        },
    'churrosolepizzeria': {
        'store_name': "Churro's Ole' Pizzeria", 
        'store_category': 'food', 
        'sub_categories': ['pizza'],
        'mapkeys': [73],
        },
    'claires': {
        'store_name': "Claire's", 
        'store_category': 'accessories', 
        'sub_categories': ['purses'],
        'mapkeys': [104],
        },  
    # 'cricket': {
    #     'store_name': 'Cricket Wireless', 
    #     'store_category': 'electronics', 
    #     'sub_categories': ['cellphones'],
    #     'mapkeys': [],
    #     },
    'dcwesternwear': {
        'store_name': "DC Western Wear", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'mensclothing'],
        'mapkeys': [119],
        },
    'deseretbook': {
        'store_name': 'Deseret Book', 
        'store_category': 'gifts', 
        'sub_categories': ['books'],
        'mapkeys': [2],
        },
    'diamondwireless': {
        'store_name': 'Diamond Wireless', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkeys': [97],
        },
    'edible': {
        'store_name': 'Edible Arrangements', 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkeys': [3],
        },
    'fadsnfashions': {
        'store_name': "Fads N' Fashions", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing'],
        'mapkeys': [46],
        },
    'famousfootwear': {
        'store_name': 'Famous Footwear', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkeys': [40],
        },  
    'fanzz': {
        'store_name': 'Fanzz', 
        'store_category': 'clothing', 
        'sub_categories': ['mensclothing', 'boysclothing'],
        'mapkeys': [98],
        },
    'footaction': {
        'store_name': 'Foot Action', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkeys': [57],
        },  
    'footlocker': {
        'store_name': 'Foot Locker', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkeys': [65],
        },  
    'fragranza': {
        'store_name': 'Fragranza', 
        'store_category': 'beauty', 
        'sub_categories': ['cologneperfume'],
        'mapkeys': [101],
        },
    'frogurt': {
        'store_name': 'Frogurt', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkeys': [20],
        },
    'gamegridarcade': {
        'store_name': 'Game Grid Arcade', 
        'store_category': 'electronics', 
        'sub_categories': ['videogames'],
        'mapkeys': [123],
        },
    'gamepeddler': {
        'store_name': 'The Game Peddler', 
        'store_category': 'electronics', 
        'sub_categories': ['videogames'],
        'mapkeys': [112],
        },  
    'gnc': {
        'store_name': 'GNC', 
        'store_category': 'beauty', 
        'sub_categories': ['health'],
        'mapkeys': [53],
        },
    'greekkabob': {
        'store_name': 'Greek Kabob', 
        'store_category': 'food', 
        'sub_categories': ['mediterranean'],
        'mapkeys': [74],
        },
    'hammond': {
        'store_name': 'Hammond', 
        'store_category': 'gifts', 
        'sub_categories': ['toys'],
        'mapkeys': [87],
        },  
    'hotdogstick': {
        'store_name': 'Hot Dog on a Stick', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkeys': [76],
        },
    # 'ikustomz': {
    #     'store_name': 'iKUSTOMZ', 
    #     'store_category': 'electronics', 
    #     'sub_categories': ['phoneaccessories'],
    #     'mapkeys': [],
    #     },  
    'jambajuice': {
        'store_name': 'Jamba Juice', 
        'store_category': 'food', 
        'sub_categories': ['juice'],
        'mapkeys': [31],
        },
    'jbvariety': {
        'store_name': 'JB Variety', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing', ],
        'mapkeys': [121],
        },  
    'jcpenney': {
        'store_name': 'J.C. Penney', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing', 
            'mensclothing', 'boysclothing', 'babyclothing', ],
        'mapkeys': [34],
        },
    'jimmyjohns': {
        'store_name': "Jimmy John's", 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [14],
        },
    'jolene': {
        'store_name': "Jolene's Girl's Dresses", 
        'store_category': 'clothing', 
        'sub_categories': ['girlsclothing'],
        'mapkeys': [126],
        },
    'journeys': {
        'store_name': "Journey's", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing'],
        'mapkeys': [58],
        },
    # 'joyeria': {
    #     'store_name': "Joyeria", 
    #     'store_category': 'jewelry', 
    #     'sub_categories': ['everyday'],
    #     'mapkeys': [],
    #     },  
    'kayjewelers': {
        'store_name': "Kay Jewelers", 
        'store_category': 'jewelry', 
        'sub_categories': ['fine'],
        'mapkeys': [59],
        },
    'kidsfashion': {
        'store_name': "Kid's Fashion", 
        'store_category': 'clothing', 
        'sub_categories': ['girlsclothing', 'boysclothing'],
        'mapkeys': [92],
        },
    # 'lacuts': {
    #     'store_name': 'L.A. Cuts', 
    #     'store_category': 'beauty', 
    #     'sub_categories': ['hair'],
    #     'mapkeys': [87],
    #     },
    'lhmmegaplex': {
        'store_name': 'Larry H. Miller Megaplex', 
        'store_category': 'movies', 
        'sub_categories': ['imax', 'standard'],
        'mapkeys': [35],
        },
    'macys': {
        'store_name': "Macy's", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing', 'babyclothing', ],
        'mapkeys': [37],
        },
    'maurices': {
        'store_name': "Maurice's", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkeys': [62],
        },
    'mdphotography': {
        'store_name': 'MD Photography', 
        'store_category': 'gifts', 
        'sub_categories': ['photography'],
        'mapkeys': [128],
        },  
    'modabella': {
        'store_name': "Moda Bella", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkeys': [55],
        },
    'morganjewelers': {
        'store_name': "Morgan Jewelers", 
        'store_category': 'jewelry', 
        'sub_categories': ['fine'],
        'mapkeys': [105],
        },
    'movies9': {
        'store_name': 'Movies 9', 
        'store_category': 'movies', 
        'sub_categories': ['standard'],
        'mapkeys': [36],
        },
    # 'mrscav': {
    #     'store_name': "Mrs. Cavanaugh's", 
    #     'store_category': 'food', 
    #     'sub_categories': ['snacks'],
    #     'mapkeys': [141],
    #     },
    'nerdstore': {
        'store_name': 'The Nerd Store', 
        'store_category': 'gifts', 
        'sub_categories': ['collectibles'],
        'mapkeys': [52],
        },  
    'nikkisbridal': {
        'store_name': "Nikki's Bridal", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkeys': [124],
        },
    'olivegarden': {
        'store_name': "Olive Garden", 
        'store_category': 'food', 
        'sub_categories': ['mediterranean'],
        'mapkeys': [1],
        },
    'orangejulius': {
        'store_name': 'Orange Julius', 
        'store_category': 'food', 
        'sub_categories': ['juice'],
        'mapkeys': [81],
        },
    'osakajapan': {
        'store_name': 'Osaka Japan', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkeys': [77],
        },
    'passionnails': {
        'store_name': 'Passion Nails', 
        'store_category': 'beauty', 
        'sub_categories': ['nails'],
        'mapkeys': [114],
        },
    'payless': {
        'store_name': 'Payless Shoe Source', 
        'store_category': 'shoes', 
        'sub_categories': ['womensshoes', 'mensshoes'],
        'mapkeys': [122],
        },
    'petco': {
        'store_name': 'PetCo', 
        'store_category': 'home', 
        'sub_categories': ['pets'],
        'mapkeys': [15],
        },
    'popcorncottage': {
        'store_name': 'Popcorn Cottage', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkeys': [109],
        },
    'pretzelmaker': {
        'store_name': 'Pretzel Maker', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkeys': [116, 117],
        },
    'purseplus': {
        'store_name': 'Purse Plus', 
        'store_category': 'accessories', 
        'sub_categories': ['purses'],
        'mapkeys': [111],
        },  
    'radioshack': {
        'store_name': 'RadioShack', 
        'store_category': 'electronics', 
        'sub_categories': ['computers', 'phoneaccessories', 'cellphones'],
        'mapkeys': [51],
        },  
    # 'rave': {
    #     'store_name': 'Rave', 
    #     'store_category': 'clothing', 
    #     'sub_categories': ['womensclothing'],
    #     'mapkeys': [104],
    #     },
    'redrobin': {
        'store_name': 'Red Robin', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [38],
        },
    'ricevillage': {
        'store_name': 'Rice Village', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkeys': [80],
        },
    'ross': {
        'store_name': 'ROSS', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing',
            'mensclothing', 'boysclothing', 'babyclothing', ],
        'mapkeys': [39],
        },
    # 'rue21': {
    #     'store_name': 'rue 21', 
    #     'store_category': 'clothing', 
    #     'sub_categories': ['womensclothing'],
    #     'mapkeys': [],
    #     },
    'rumbi': {
        'store_name': 'Rumbi', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkeys': [23],
        },
    # 'ryanscustomjewelry': {
    #     'store_name': "Ryan's Custom Jewelry", 
    #     'store_category': 'jewelry', 
    #     'sub_categories': ['watches', 'fine'],
    #     'mapkeys': [44],
    #     },
    'schubachjewelers': {
        'store_name': "Schubach Jewelers", 
        'store_category': 'jewelry', 
        'sub_categories': ['fine'],
        'mapkeys': [115],
        },
    # 'shoemania': {
    #     'store_name': 'Shoe Mania', 
    #     'store_category': 'shoes', 
    #     'sub_categories': ['womensshoes', 'mensshoes'],
    #     'mapkeys': [],
    #     },
    # 'shoeoutlet': {
    #     'store_name': 'Shoe Outlet', 
    #     'store_category': 'shoes', 
    #     'sub_categories': ['womensshoes', 'mensshoes'],
    #     'mapkeys': [],
    #     },
    # 'silverloft': {
    #     'store_name': "Silver Loft", 
    #     'store_category': 'jewelry', 
    #     'sub_categories': ['everyday'],
    #     'mapkeys': [139],
    #     },  
    'smashburger': {
        'store_name': 'Smashburger', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [5],
        },
    # 'sprint': {
    #     'store_name': 'Sprint', 
    #     'store_category': 'electronics', 
    #     'sub_categories': ['cellphones'],
    #     'mapkeys': [149],
    #     },
    'subway': {
        'store_name': 'Subway', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [75],
        },
    'sushimonster': {
        'store_name': 'Sushi Monster', 
        'store_category': 'food', 
        'sub_categories': ['asian'],
        'mapkeys': [29],
        },
    'sweet16': {
        'store_name': "Sweet 16", 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing', 'girlsclothing'],
        'mapkeys': [64],
        },
    'sweettoothfairy': {
        'store_name': 'Sweet Tooth Fairy', 
        'store_category': 'food', 
        'sub_categories': ['snacks'],
        'mapkeys': [26],
        },
    'tgifridays': {
        'store_name': 'TGI Fridays', 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [33],
        },
    'tieoneon': {
        'store_name': 'Tie One On', 
        'store_category': 'accessories', 
        'sub_categories': ['neckwear'],
        'mapkeys': [106],
        },  
    'tmobile': {
        'store_name': 'T-Mobile', 
        'store_category': 'electronics', 
        'sub_categories': ['cellphones'],
        'mapkeys': [96],
        },
    'trinketstreasures': {
        'store_name': "Trickets n' Treasures", 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkeys': [47],
        },
    'tropicaljuice': {
        'store_name': 'Tropical Juice', 
        'store_category': 'food', 
        'sub_categories': ['juice'],
        'mapkeys': [68],
        },
    'ulta': {
        'store_name': 'Ulta Beauty', 
        'store_category': 'home', 
        'sub_categories': ['home'],
        'mapkeys': [43],
        },
    'uniquegifts': {
        'store_name': "Unique Gifts", 
        'store_category': 'gifts', 
        'sub_categories': ['miscgifts'],
        'mapkeys': [91],
        },  
    'urbanexpress': {
        'store_name': 'Urban Express', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing'],
        'mapkeys': [82],
        },
    'westvalleymusic': {
        'store_name': "West Valley Music", 
        'store_category': 'gifts', 
        'sub_categories': ['musicalinst'],
        'mapkeys': [129],
        },
    'wingers': {
        'store_name': "Winger's", 
        'store_category': 'food', 
        'sub_categories': ['sandwiches'],
        'mapkeys': [13],
        },
    # 'xbrands': {
    #     'store_name': 'X-Brands Custom T-Shirts', 
    #     'store_category': 'clothing', 
    #     'sub_categories': ['womensclothing', 'girlsclothing',
    #         'mensclothing', 'boysclothing'],
    #     'mapkeys': [109],
    #     },
    'xzone': {
        'store_name': 'X-Zone', 
        'store_category': 'clothing', 
        'sub_categories': ['womensclothing','mensclothing'],
        'mapkeys': [49],
        },
    'zagg': {
        'store_name': 'ZAGG', 
        'store_category': 'electronics', 
        'sub_categories': ['phoneaccessories'],
        'mapkeys': [84],
        },  
    # 'zumiez': {
    #     'store_name': 'Zumiez', 
    #     'store_category': 'clothing', 
    #     'sub_categories': ['womensclothing', 'girlsclothing',
    #         'mensclothing', 'boysclothing'],
    #     'mapkeys': [64],
    #     },
    'bathrooms': {
        'store_name': 'Bathrooms',
        'store_category': 'bathrooms',
        'sub_categories': [],
        'mapkeys': [70],
        },
    }